### ISSUE TITLE
Animations make me angry...

### ISSUE THREAD

**Issue by tradzik** [FOSSASIA-Web/gci14.fossasia.org#107]
Please remove some of animations on this website. Really irritating is scrolling list of mentors/stundets - it is laggy and I can quickly find that what I want. That makes this website looking infantile. 

Please take a look, e.g. on FOSSASIA.ORG. It is simple and fine. It doesn't have unneccesary, annoying animations...

**Comment by roonyh** [comment]
Hi! Thanks for your ideas and suggestions! We already have an open issue and discussion about this at #55. Please place your ideas there instead of opening a new one.

**Comment by tradzik** [comment]
I prefered to open new one, these existing looks deadly ;-) BTW Can you
@roonyh review this one my task :
http://www.google-melange.com/gci/task/view/google/gci2014/5909722544734208

Fri Dec 19 2014 at 22:54:36 użytkownik Aruna Herath <
notifications@github.com> napisał:

**Comment by roonyh** [comment]
No open issue is dead :)
Its organized when things regarding one thing is in one place. You are more likely get other people's ideas there because people who participated in the discussion will get notified of new comments.

I am sorry but I have no idea about that issue :(

**Comment by roonyh** [comment]
Sorry I meant t I have no idea about that task!
