### ISSUE TITLE
Does the sidebar toggle work?

### ISSUE THREAD

**Issue by namangoel1** [FOSSASIA-Web/gci14.fossasia.org#139]
I am unable to get it to work on my end. Is it just me or does it not work?

I simply see the icon shifted a bit to the right, like this http://i.imgur.com/LU52YO5.png

**Comment by XTremeRox** [comment]
Actually, when I had made the commit for that sidebar, It worked well, but after that, somebody messed up with that sidebar so, now I don't know which commit to blame, @mariobehling @RoonyH think we should have a look at this, cuz this has rendered my sidebar totally useless. :(

**Comment by namangoel1** [comment]
Some of my own changes were over-written. I guess this is a problem with merging and conflicts, since there are a lot of simultaneous pull requests. Once the mentors reply I guess you'll have to do it again :S

In the next iteration, could you ensure that you put each style in style.css using media queries instead of having 3 different stylesheets?

**Comment by amramadan** [comment]
Hey, I have been searching for the error which caused, the thing is that if tou go to the stylesheet of the sidebar (sidebar-style) and change the sidebar class's left from -190 to 5 for example the sidebar will appear, and yet the animation or the motion of the menu bar on the website is the bug so check the javascript I didnt have time to check it yet. And lets work together to fix this :D

**Comment by namanyayg** [comment]
@RoonyH can be closed now. We don't use a sidebar :P
