### ISSUE TITLE
Google code-in

### ISSUE THREAD

**Issue by ou29tyle** [FOSSASIA-Web/gci14.fossasia.org#164]
Using it on mobile device is annoying

**Comment by ou29tyle** [comment]
There isn't a link for Google+

**Comment by wongalvis** [comment]
@ou29tyle Would you describe a bit about what makes it annoying and tell us your suggestions if you have them in your mind

**Comment by wongalvis** [comment]
Regarding the link for Google+ the problem has not appeared locally in my machine, is it a persistent issue?

**Comment by namanyayg** [comment]
A better description will be appreciated, @ou29tyle
