### ISSUE TITLE
Where is the menu?

### ISSUE THREAD

**Issue by chaconne7** [FOSSASIA-Web/gci14.fossasia.org#237]
What happened to the menu on larger browsers and devices? I don't think the user should have to scroll down the whole page to get to the part he wants. The menu looks great on mobile devices, but there should be a menu in the header on non-mobile devices, too!

![fossasia desktop screenshot](https://cloud.githubusercontent.com/assets/6181251/5663720/51ab615c-9718-11e4-8fdb-25ad4df65262.jpg)

![fossasia mobile screenshot](https://cloud.githubusercontent.com/assets/6181251/5663729/68cbd9a2-9718-11e4-88ac-530e2c5dc023.jpg)

**Comment by namangoel1** [comment]
Tap the menu icon, @chaconne7 . I think this can be closed @RoonyH

**Comment by chaconne7** [comment]
I don't see a menu icon when my browser is at full size, though. The menu icon only shows up when I make the browser smaller.

**Comment by namangoel1** [comment]
@chaconne7 What is your screen resolution?

**Comment by namangoel1** [comment]
@chaconne7 Nevermind, got it. Happens at a very small window of screen width. Going to fix. Thanks a ton!

**Comment by namangoel1** [comment]
Fixed in #225
