### ISSUE TITLE
Banner is not responsive

### ISSUE THREAD

**Issue by chaconne7** [FOSSASIA-Web/gci14.fossasia.org#238]
When I resize the Google Chrome window, the banner isn't responsive. 

![fossasia mobile screenshot](https://cloud.githubusercontent.com/assets/6181251/5663796/02f54a22-9719-11e4-9176-17d0ec2563b1.jpg)

**Comment by namangoel1** [comment]
Refresh the page @chaconne7 . Due to the restrictions of the slider it can't be made responsive on screen resize. Fortunately, no one resizes their screen.

**Comment by chaconne7** [comment]
Okay, thanks, @namangoel1! I didn't realize that. Unfortunately the image is still goofy when I refresh the page, though. The image is split in two: the top part is displayed, then the full image, then the bottom part.

![fossasia mobile 3](https://cloud.githubusercontent.com/assets/6181251/5664237/d7f8d6fa-971c-11e4-8b8f-e4f1d53f4c8d.jpg)

![fossasia mobile 2](https://cloud.githubusercontent.com/assets/6181251/5664239/dc482fe4-971c-11e4-90a4-459e18c4f201.jpg)

**Comment by namangoel1** [comment]
@chaconne7 Thanks, I'll push a fix for this too and then ask you to have a look :)

**Comment by chaconne7** [comment]
Cool! Looking forward to seeing how you change the code.

**Comment by namangoel1** [comment]
Fixed in #225. Preview [here](http://namangoel1.github.io/fossasia.github.io)
