### ISSUE TITLE
[Amirul] Issue 02: Make the icon for each Mentor link to their respective contact page

### ISSUE THREAD

**Issue by amrl** [FOSSASIA-Web/gci14.fossasia.org#24]
![error2](https://cloud.githubusercontent.com/assets/7194927/5335868/a4ea98f8-7eed-11e4-9152-1cc6453bd65c.png)

Suggestion:
Have the icons link to various services for contact (eg. Facebook, Twitter, Email) Quite important to get in touch with the Mentors.

**Comment by namangoel1** [comment]
Already there, try to hover over a mentor.

**Comment by amrl** [comment]
Ah for some reason I could only see the small icons when hovering over the Students just now. Tried it again and I can now see the Github links for the Mentors. Not sure what happened just now but I guess everything's currently working fine.

**Comment by namangoel1** [comment]
Was a feature since the start, must be a weird bug. Please close the issue
if everything is cool :)
