### ISSUE TITLE
[Amirul] Issue 03: Suggested rewrite of ending sentence

### ISSUE THREAD

**Issue by amrl** [FOSSASIA-Web/gci14.fossasia.org#25]
![error3](https://cloud.githubusercontent.com/assets/7194927/5335885/d3c8764a-7eed-11e4-9e1e-26c585056b95.png)

Rewrite as:
THANK YOU FOR ALL YOUR CONTRIBUTIONS!

**Comment by roonyh** [comment]
Thanks for the suggestion! We would like to keep the current text for now.
