### ISSUE TITLE
some links in Mentors section not showing up

### ISSUE THREAD

**Issue by izzylys** [FOSSASIA-Web/gci14.fossasia.org#258]
Hello!

I was working in the json file for the mentors and I noticed that some of the mentors have more than one link to a personal blog/website, but the github site only displays the last of their links.  The people affected by this are Michael Cheng, Andres Colubri, Hon Nguyen, and Tong Hui.  I'm not super familiar with programming so I am really not sure how to remedy this.  If anyone has any insight they could contribute, it would be much appreciated!

Thanks,
Izzy

**Comment by tradzik** [comment]
Thank you for pointing that! Will be fixed ASAP

**Comment by samarsault** [comment]
@ty221, that's json which doesn't accept the same keys in a dictionary maybe a link2 will do ?

**Comment by tradzik** [comment]
It is illegal to add fields with same key in JSON, that is why their keys
need to be changed. "Link2" should work. I will submit my changes in a few
minutes.
