### ISSUE TITLE
[gci] Initial Suggestions

### ISSUE THREAD

**Issue by ribhu97** [FOSSASIA-Web/gci14.fossasia.org#27]
Firstly, there is a spelling error : 

![2014-12-08 15_20_07-fossasia gci](https://cloud.githubusercontent.com/assets/6207389/5337393/e7c757ce-7eed-11e4-851e-7f1ca518dfaa.png)

It should be "is".

Next up, I would like to suggest you guys go for parallax scrolling for more aesthetic pleasure.
I was looking through your blog, and I could see a few pictures that you guys could use as the backdrops, or maybe even use some stock photos.
For reference on parallax scrolling I would suggest:
Javascript and CSS  - https://ihatetomatoes.net/simple-parallax-scrolling-tutorial/
Pure CSS - http://davidwalsh.name/parallax
If you are a programmer, the javascript method is easier, but if you are a web dev then the pure CSS will be more your speed.

Again, form your blogs, I saw that you guys had a few events over the years. Why not make a sort of nav-bar below the header that can cycle through your annual events. Sort-of like:
![2014-12-08 15_33_26-fossasia gci](https://cloud.githubusercontent.com/assets/6207389/5337522/ab5bcba6-7eef-11e4-8d14-a3b5c64b8fe7.png)

Finally, This last section just above the footer:

![2014-12-08 15_35_21-fossasia gci](https://cloud.githubusercontent.com/assets/6207389/5337546/da8c473e-7eef-11e4-8fb1-e954e7f1cb9d.png)

This looks a little out of place. Firstly, since the site is in English maybe just the English (corrected) "Thank you for your contributions." is fine. If you like to add localisation, then add a few buttons in the footer, which changes the entire page to a certain language. Another can possibly be dynamic font, i.e. the sentence changes its language every few seconds, but that does not seem very aesthetically pleasing. Secondly, since there are 7 icons, maybe arrange them in a 3-3-1 way. Or arrange all in one row. 

I think that's all I think that can initially be done. If you require any help or any other suggestion please feel free to contact

**Comment by roonyh** [comment]
Thank you very much! We really value your feedback. It will be great if you can submit your different ideas as separate issues. Would that be possible? Thanks again!

**Comment by roonyh** [comment]
Typo is fixed.
We have an open pull request #71 for parallax scrolling.
fossasia annual events are kind of not related to this website. This is about GCI and its students and mentors.
Number of contributors is not limited to 7. It increases with each commit from a new contributor. So we like the current layout.
