### ISSUE TITLE
Vamshi  

### ISSUE THREAD

**Issue by ghost** [FOSSASIA-Web/gci14.fossasia.org#31]
Uploading my picture.

![smz50dae3l327007 smz51998b27aefd82 34200511](https://cloud.githubusercontent.com/assets/10115553/5340677/6556976e-7f15-11e4-957e-cdddfc319b15.jpg)

**Comment by ghost** [comment]
I'm having trouble uploading my picture to the repository.

**Comment by PolBaladas** [comment]
Have you modified the HTML code with the exactly same file name as you picture in the images folder?
see you

**Comment by roonyh** [comment]
Picture is added to the site.
