### ISSUE TITLE
Header is not responsive

### ISSUE THREAD

**Issue by Legoben** [FOSSASIA-Web/gci14.fossasia.org#52]
Takes up over half of the page on mobile

![screenshot](http://i.imgur.com/EBS0xW2.png)

**Comment by mariobehling** [comment]
I created a task here for this issue. Please claim it, if you are interested: http://www.google-melange.com/gci/task/view/google/gci2014/5823617258487808

**Comment by roonyh** [comment]
@Legoben Thank you very much for the report!

@fossasia/fossasia-gci-students Any one of you interested to fix this and complete the task?

**Comment by chaconne7** [comment]
I would, but I'm waiting for my other task to be closed!

**Comment by roonyh** [comment]
@chaconne7 please give me a link to the task.

**Comment by chaconne7** [comment]
https://www.google-melange.com/gci/task/view/google/gci2014/5009353266429952

**Comment by chaconne7** [comment]
Thank you for closing it!

**Comment by roonyh** [comment]
@chaconne7 Hi! How is this work comming? If you need any help please comment here.

**Comment by chaconne7** [comment]
I worked on it for a while tonight, so that a menu button appears (and the rest of the heading links disappear) when the screen size drops below 40px. I'm just trying to fix the CSS - the dropdown menu for the button is cut off by the bottom of the header. I'm going to work on this more tomorrow, since the task is due tomorrow night.

**Comment by roonyh** [comment]
That sounds awsome. Don't worry too much about the deadline. We can extend it a day or two. But sooner the better. :)
And you can make a pull request with your current code and throw in more commits later.

**Comment by chaconne7** [comment]
Okay, I put in a pull request. I'll work on fixing the cut-off menu tomorrow! Thank you for extending the deadline!

**Comment by chaconne7** [comment]
Agh - I'm having too many problems with this, and I don't have time to fix them. I'm going to unclaim this task.

**Comment by roonyh** [comment]
@chaconne7 I wish I could have been more helpful. But I am a little busy this week. Feel free to claim any other task or even this one if you figure it out. Thanks for your work so far!

**Comment by roonyh** [comment]
[fixed here](https://github.com/fossasia/fossasia.github.io/commit/8026ec3cebdb902cc91bcd271a8665642cd545d2) with the addition of side bar
