### ISSUE TITLE
MAP

### ISSUE THREAD

**Issue by amanahmed** [FOSSASIA-Web/gci14.fossasia.org#54]
There was an error while I was using zoom out tool.
If I moved the cursor to the right or left by mistake clicking the zoom out tool the the tool also moved.
This usually does not happen on other map sites,eg.Google Maps
![fossasia errors](https://cloud.githubusercontent.com/assets/10146596/5388174/3c12a250-810c-11e4-99ea-41cd99da7394.png)

**Comment by roonyh** [comment]
Hi! Thanks for checking checking out our site and reporting this! Can you reproduce this? It doesn't happen when I zoom out.

**Comment by amanahmed** [comment]
Hi!
Yes I can reproduce it again,this time I did this this with the navigator tool.It exactly happens when i click that tool and by mistake move it to the left or right,the zoom in ,zoom out,and the navigator tool,all have the same errors.
There was one more problem which I encountered this time,I have encircled it,please have a look.
![untitled](https://cloud.githubusercontent.com/assets/10146596/5391934/e37a801e-8146-11e4-97b5-e08c35442f44.png)

**Comment by roonyh** [comment]
Cannot reproduce this. Probably a local issue.
