### ISSUE TITLE
Too many animations?

### ISSUE THREAD

**Issue by namangoel1** [FOSSASIA-Web/gci14.fossasia.org#55]
Including the wow.js library not only increases the page load time, but the animations look a bit too excessive. Can we remove those?

**Comment by roonyh** [comment]
Yeah I noted that too. Maybe we can decrease the animations. I propose we should keep wow.js and only add a simple animation to pictures. @fossasia/fossasia-gci-students what do you folks think? Comment your ideas.

**Comment by PolBaladas** [comment]
Yeah it's a bit excessive, I agree on that. Too many anims can drive you crazy. We could do what Roonyh says if no one has another idea.

**Comment by tradzik** [comment]
I think roonyh is Aruna (?) :-)

Thu Dec 11 2014 at 20:33:49 użytkownik Pol Baladas Luna <
notifications@github.com> napisał:

**Comment by PolBaladas** [comment]
Yes, but RoonyH it's the github username. Anyway, that has nothing to do with the subject we're working on here.

**Comment by tradzik** [comment]
Yes, that's true. It has nothing to do with your subject. I only wanted to
mark quite interesting thing for me. You were talking to Aruna and using
RoonyH as other person... Now I think we should close this spammy
disscusion :-)

**Comment by roonyh** [comment]
@ty221 what do you think about the animations?

**Comment by tradzik** [comment]
I think animations are ok, but there are too much of them. I hate when
every part of website is moving, blinking, etc. That's annoying. I suggest
to keep some basic animations (e.g. students' images), but remove others.
There is also one possibility - we can make "Enable extended animation"
button (e.g. in JS) - it will enable more animations that those basic ones
:)

**Comment by namangoel1** [comment]
@ty221 I think having the button will be redundant, have you ever seen any such button on any site? Extreme animations make the site look a bit childish. I vote that we convert all animations to basic fade ones. Thoughts?

BTW @RoonyH could you look into http://www.google-melange.com/gci/task/view/google/gci2014/5545657376964608 ? I'm pretty certain I've hit all requirements properly (and even have went a bit beyond), just waiting for the task to be closed.

Thanks!

**Comment by roonyh** [comment]
Lets keep animations only to pictures and make them basic ones. Thanks for suggestions. Can one of you go ahead and submit a pull request with this work?

And btw @fossasia/fossasia-gci-students fyi: https://github.com/fossasia/fossasia.github.io#gci-students-guide :wink:

@namangoel1 That's a very interesting task. I'll look at your code in when I have some free time. But lets wait a bit for the mentor to review it.

**Comment by JamesOnnen** [comment]
Google Code-in student here, but I love motion design and UX.

In my opinion, I enjoy the animations, but the transitions initiated on scroll are triggered _by_ the scroll, not linked to the scroll. Personally, I would link the transition state to be with the scrolling state, which might help make it feel graceful.

Unfortunately, when you do this, it ends up being choppy on browsers without smooth scrolling, so a bit of CSS transitions (I'm not well versed on these), should (maybe?) fix this?

**Comment by roonyh** [comment]
@JamesOnnen Thanks much for your ideas. I'll look into that. I too am no CSS expert. I am usually stuck at the back end. Btw you are welcome to add you picture and links to our site if you don't mind.

**Comment by namangoel1** [comment]
@RoonyH Is it okay if I replace the animations by something more subtle and create a pull request? Thanks!

**Comment by roonyh** [comment]
So @namangoel1 made some changes regarding this. What do others think of the new look? Shall we close this issue?

**Comment by samarsault** [comment]
I guess that the update is much better looking and performance friendly than the previous site which was full of unnecessary animations !!

**Comment by ghost** [comment]
Looks good to me!

**Comment by mariobehling** [comment]
At the moment there are errors with animations loading on page load.

**Comment by namangoel1** [comment]
Seems like the animations are back? @RoonyH ?

**Comment by roonyh** [comment]
Well, user interfaces are hard! Its hardly possible to please every user. And the fact that our users mainly are teenagers aged 13-17 makes it even harder. What seems flashy and beautiful to a 13 year-old could be irritating and boring to a 17 year-old. Anyway our idea is that this website should be a flashy one for kids. @mariobehling could provide more on that. So yeah lets keep the animations on for now. I personally feed they could be lot more organized and subtle. But lets worry about more important issues like the broken and disorganized mobile version for now. This issue will be kept open and lets get back to it later. Ok?

**Comment by namangoel1** [comment]
@RoonyH Got it, flashy animations are back again.

**Comment by namangoel1** [comment]
@RoonyH btw, you free to come on irc?

**Comment by mariobehling** [comment]
Closed as discussed. Open new thread if issue arises again.
