### ISSUE TITLE
New section for FOSSASIA Photos and fix twitter feed

### ISSUE THREAD

**Issue by mbelchev** [FOSSASIA-Web/gci14.fossasia.org#61]
<img src="http://store.picbg.net/pubpic/A9/1E/23507e44c5caa91e.png" alt="screenshot" />

It looks a bit improperly. It will be better if you move Photos section on new row.

**Comment by roonyh** [comment]
I agree. @udeepak What do you think? Can you make this change?

**Comment by samarsault** [comment]
Yes, it does looks crowded and I was about to create an issue on that. I guess Another section can be created for the flickr photostream and it can be made full width.

**Comment by mbelchev** [comment]
Totally agree with you! If no one wants to do it i will fix it later. :)

**Comment by udeepak** [comment]
Sure. I can do that. :) Will probably do it tomorrow. :)

**Comment by roonyh** [comment]
@udeepak great! thank you very much!

**Comment by roonyh** [comment]
Fixed by #68
