### ISSUE TITLE
Wrong Date in the FOSSASIA Blog

### ISSUE THREAD

**Issue by Zoometric** [FOSSASIA-Web/gci14.fossasia.org#66]
The blog post at:
http://blog.fossasia.org/fossasia-joining-google-code-program-students-age-13-17
has the incorrect year twice, 2015 instead of 2014.
![fossasiascreenshot1](https://cloud.githubusercontent.com/assets/10168367/5424558/5ddfe924-82ba-11e4-924c-bfc87c8be2ed.png)

**Comment by mariobehling** [comment]
Good job! Thank you so much!
