### ISSUE TITLE
Hard to Read Text in the Opening Banner

### ISSUE THREAD

**Issue by Zoometric** [FOSSASIA-Web/gci14.fossasia.org#67]
The text in the opening banner is really hard to read, I have some ideas on how to fix it.
First, how it looks now:
![fossasiascreenshot2](https://cloud.githubusercontent.com/assets/10168367/5424635/8b0cc24c-82be-11e4-9d54-d1c84692c47f.png)
Second, how I think it should look.  Please excuse my lack of artistic ability, and instead envision something with better-looking edges around the text islands.
![fossasiascreenshot2fixed](https://cloud.githubusercontent.com/assets/10168367/5424638/a5948fd2-82be-11e4-8e22-98b7fb2cbc54.png)

**Comment by roonyh** [comment]
@Zoometric this should be fixed by now. Can you please check and confirm?

**Comment by Zoometric** [comment]
Yes, that looks much better!
