### ISSUE TITLE
The menu button in mobile does not show up correctly

### ISSUE THREAD

**Issue by hossainalikram** [FOSSASIA-Web/gci14.fossasia.org#84]
If I try to browse Foss Asia's GCI's site from mobile , the menu button is not showig correctly , It is having an overlaying problem. The content and the menu mixes together , So , it looks bad.

**Comment by roonyh** [comment]
Thanks for submitting this! Can you please upload a screen shot. Will be easier to figure out the problem.

**Comment by hossainalikram** [comment]
Here is a link of screen shot https://drive.google.com/file/d/0B5lhtIMj3Gh0WW1yY1hGV1VTLWc/view?usp=sharing

**Comment by hossainalikram** [comment]
Some more screenshot of this issue
1. https://drive.google.com/file/d/0B5lhtIMj3Gh0bmp6LUE4bTVVMDg/view?usp=sharing
   2.https://drive.google.com/file/d/0B5lhtIMj3Gh0U3B2OE13ZGFKakU/view?usp=sharing
2. https://drive.google.com/file/d/0B5lhtIMj3Gh0QTBNSEpjTDRocGc/view?usp=sharing
   4.https://drive.google.com/file/d/0B5lhtIMj3Gh0ZjU1VHJ3WWd2RDA/view?usp=sharing

**Comment by roonyh** [comment]
@hossainalikram You can attach photos directly to your comments instead of submitting links :) 
![nokia n9](https://cloud.githubusercontent.com/assets/3872221/5501142/bfc2a91e-877a-11e4-8a34-b016cd96dedc.JPG)

And do you have a idea about what would be the fix for this? Maybe send us a mock interface?
@XTremeRox thought you might be interested in this conversation :)

**Comment by hossainalikram** [comment]
@RoonyH  thanks for the image upload thing , I did not knew that :smile: 

And thanks @XTremeRox  for thinking about me :) . I want to try about it . If possible , I will try for some user interface task soon :smile:  But seems , no task is available right now :worried:

**Comment by XTremeRox** [comment]
I actually, didn't get the problem, the menu is a float type menu button, so it is designed to do so, though if you would be able to elaborate, I will see see what I can do about it :) Thanks, for that review by the way!

**Comment by roonyh** [comment]
Lets keep this closed for now since its not that important. But get back when we don't have more important issues.

**Comment by XTremeRox** [comment]
No, this ain't happening :'( somebody messed up with my code again, the sidebar ain't working!
