### ISSUE TITLE
Some same image are showing for people 

### ISSUE THREAD

**Issue by hossainalikram** [FOSSASIA-Web/gci14.fossasia.org#85]
Recently , in FossAsia's GCI website , I am seeing a huge number of same kind of pictures , which are used for various people. But it is looking bad , If they don't want to give pictures , we can up any other stock image but current situation is not looking good :/

**Comment by hossainalikram** [comment]
Screenshot of the issuue https://drive.google.com/file/d/0B5lhtIMj3Gh0ZjU1VHJ3WWd2RDA/view?usp=sharing

**Comment by roonyh** [comment]
Thanks but these are placeholders for mentors who have not uploaded their images yet. No need to track a issue. :smile:
