### ISSUE TITLE
The photo stream doesn't work in mobile

### ISSUE THREAD

**Issue by hossainalikram** [FOSSASIA-Web/gci14.fossasia.org#86]
If i try to browse in the site , in photo stream section i see a black image , nothing else , so it's looking worse , and another thing it's half portion is showing in regular screen , I mean it have some responsive issue too

**Comment by akshattripathi** [comment]
Fixed.

**Comment by akshattripathi** [comment]
Also, you have to wait till the photostream loads, it may take a while.

**Comment by namanyayg** [comment]
@RoonyH please close now, fixed.
