### ISSUE TITLE
Twitter feed is annoying in Mobile

### ISSUE THREAD

**Issue by hossainalikram** [FOSSASIA-Web/gci14.fossasia.org#87]
The most annoying thing of the site looks from me , is the twitter feed. I have felt this from mobile view. If i go to twitter feed from a small screen mobile , then , Sometimes , I have to scroll the whole twitter feed to go down of the page. Its annoying for the small screen mobiles

**Comment by samarsault** [comment]
hi @hossainalikram have you checked the latest version ?

**Comment by roonyh** [comment]
I think this is fixed now. Please reopen if not.
