### ISSUE TITLE
The bottom portion doesn't looks organized in mobile

### ISSUE THREAD

**Issue by hossainalikram** [FOSSASIA-Web/gci14.fossasia.org#88]
In mobile , if you go to the very bottom of the page , it looks unorganized.This is a screenshot i have taken from my mobile https://drive.google.com/file/d/0B5lhtIMj3Gh0QTBNSEpjTDRocGc/view?usp=sharing . This is exactly what it looks like , If the contents are in little bit right portion , then it wouldn't look that much bad.

**Comment by roonyh** [comment]
![2015-02-16-07-39-33](https://cloud.githubusercontent.com/assets/3872221/5500995/5477d4b6-8777-11e4-9b2f-a08313d1c9ac.png)

Moving the content under **FOSSASIA LINKS** and **EVENTS** a little to right would fix this. Or even removing those small images.

**Comment by XTremeRox** [comment]
Fixed it, ahoy! Mission accomplished :)

**Comment by roonyh** [comment]
Thanks @XTremeRox!!
